In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
data = np.random.randn(4,3)

In [4]:
data

array([[ 0.73493252,  1.15312848,  0.89402664],
       [ 0.67005067,  0.52432509, -0.20150439],
       [ 1.51062725,  0.47569935, -0.41690988],
       [-0.41650595, -0.3668097 ,  0.15429954]])

In [5]:
data_frame = pd.DataFrame(data)

In [6]:
data_frame

          0         1         2
0  0.734933  1.153128  0.894027
1  0.670051  0.524325 -0.201504
2  1.510627  0.475699 -0.416910
3 -0.416506 -0.366810  0.154300

In [7]:
data_frame[0]

0    0.734933
1    0.670051
2    1.510627
3   -0.416506
Name: 0, dtype: float64

In [8]:
new_df = pd.DataFrame(data, index = ["Ali", "Beyza", "Can", "Deniz"], columns = ["Salary", "Age", "Seniority"])
new_df

         Salary       Age  Seniority
Ali    0.734933  1.153128   0.894027
Beyza  0.670051  0.524325  -0.201504
Can    1.510627  0.475699  -0.416910
Deniz -0.416506 -0.366810   0.154300

In [9]:
new_df["Age"]

Ali      1.153128
Beyza    0.524325
Can      0.475699
Deniz   -0.366810
Name: Age, dtype: float64

In [10]:
new_df[["Age", "Salary"]]

            Age    Salary
Ali    1.153128  0.734933
Beyza  0.524325  0.670051
Can    0.475699  1.510627
Deniz -0.366810 -0.416506

In [11]:
new_df.loc["Ali"]

Salary       0.734933
Age          1.153128
Seniority    0.894027
Name: Ali, dtype: float64

In [12]:
new_df.iloc[0]

Salary       0.734933
Age          1.153128
Seniority    0.894027
Name: Ali, dtype: float64

In [13]:
new_df.iloc[:,2]

Ali      0.894027
Beyza   -0.201504
Can     -0.416910
Deniz    0.154300
Name: Seniority, dtype: float64

In [14]:
new_df["Extra"] = 10

In [15]:
new_df

         Salary       Age  Seniority  Extra
Ali    0.734933  1.153128   0.894027     10
Beyza  0.670051  0.524325  -0.201504     10
Can    1.510627  0.475699  -0.416910     10
Deniz -0.416506 -0.366810   0.154300     10

In [17]:
new_df.drop("Extra", axis = 1, inplace = True)
# Extra sütununu sil axis = 1 sütun olduğunu belirtir inplace = True ise kalıcı olarak siler

In [18]:
new_df

         Salary       Age  Seniority
Ali    0.734933  1.153128   0.894027
Beyza  0.670051  0.524325  -0.201504
Can    1.510627  0.475699  -0.416910
Deniz -0.416506 -0.366810   0.154300

In [19]:
# axis = 0 ise satır siler axis = 1 ise sütun siler
new_df.drop("Beyza")

         Salary       Age  Seniority
Ali    0.734933  1.153128   0.894027
Can    1.510627  0.475699  -0.416910
Deniz -0.416506 -0.366810   0.154300

In [21]:
new_df.loc["Ali"]

Salary       0.734933
Age          1.153128
Seniority    0.894027
Name: Ali, dtype: float64

In [22]:
new_df.loc["Ali"]["Salary"]

np.float64(0.7349325247677199)

In [23]:
new_df.loc["Ali", "Salary"]

np.float64(0.7349325247677199)

In [24]:
new_df.loc["Ali", "Salary"] = 100

In [25]:
new_df

           Salary       Age  Seniority
Ali    100.000000  1.153128   0.894027
Beyza    0.670051  0.524325  -0.201504
Can      1.510627  0.475699  -0.416910
Deniz   -0.416506 -0.366810   0.154300

In [26]:
new_df > 0

       Salary    Age  Seniority
Ali      True   True       True
Beyza    True   True      False
Can      True   True      False
Deniz   False  False       True

In [27]:
new_df[new_df > 0]

           Salary       Age  Seniority
Ali    100.000000  1.153128   0.894027
Beyza    0.670051  0.524325        NaN
Can      1.510627  0.475699        NaN
Deniz         NaN       NaN   0.154300

In [28]:
new_df[new_df["Salary"] > 1]

         Salary       Age  Seniority
Ali  100.000000  1.153128   0.894027
Can    1.510627  0.475699  -0.416910

In [29]:
new_df.reset_index()

   index      Salary       Age  Seniority
0    Ali  100.000000  1.153128   0.894027
1  Beyza    0.670051  0.524325  -0.201504
2    Can    1.510627  0.475699  -0.416910
3  Deniz   -0.416506 -0.366810   0.154300

In [30]:
new_indices = ["A", "B", "C", "D"]
new_df["NewIndex"] = new_indices
new_df

           Salary       Age  Seniority NewIndex
Ali    100.000000  1.153128   0.894027        A
Beyza    0.670051  0.524325  -0.201504        B
Can      1.510627  0.475699  -0.416910        C
Deniz   -0.416506 -0.366810   0.154300        D

In [31]:
new_df.set_index("NewIndex", inplace = True)

In [32]:
new_df

              Salary       Age  Seniority
NewIndex
A         100.000000  1.153128   0.894027
B           0.670051  0.524325  -0.201504
C           1.510627  0.475699  -0.416910
D          -0.416506 -0.366810   0.154300

In [33]:
# multi index
first_index = ["Simpson", "Simpson", "Simpson", "South Park", "South Park", "South Park"]

In [34]:
inner_index = ["Homer", "Bart", "Marge", "Cartman", "Kenny", "Kyle"]

In [35]:
zipped_index = list(zip(first_index, inner_index))

In [36]:
zipped_index

[('Simpson', 'Homer'),
 ('Simpson', 'Bart'),
 ('Simpson', 'Marge'),
 ('South Park', 'Cartman'),
 ('South Park', 'Kenny'),
 ('South Park', 'Kyle')]

In [37]:
zipped_index = pd.MultiIndex.from_tuples(zipped_index)

In [38]:
zipped_index

MultiIndex([(   'Simpson',   'Homer'),
            (   'Simpson',    'Bart'),
            (   'Simpson',   'Marge'),
            ('South Park', 'Cartman'),
            ('South Park',   'Kenny'),
            ('South Park',    'Kyle')],
           )

In [39]:
sample_values = np.ones((6,2))

In [40]:
big_df = pd.DataFrame(sample_values, index=zipped_index, columns = ["Age", "Salary"])

In [41]:
big_df

                    Age  Salary
Simpson    Homer    1.0     1.0
           Bart     1.0     1.0
           Marge    1.0     1.0
South Park Cartman  1.0     1.0
           Kenny    1.0     1.0
           Kyle     1.0     1.0

In [42]:
big_df["Age"]

Simpson     Homer      1.0
            Bart       1.0
            Marge      1.0
South Park  Cartman    1.0
            Kenny      1.0
            Kyle       1.0
Name: Age, dtype: float64

In [43]:
big_df.loc["Simpson"]

       Age  Salary
Homer  1.0     1.0
Bart   1.0     1.0
Marge  1.0     1.0

In [44]:
big_df.loc["Simpson"].loc["Homer"]

Age       1.0
Salary    1.0
Name: Homer, dtype: float64